// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhxNKhmZ-xPAIXVbMuCTtsKyG4qMyXGR0',
    appId: '1:578243094632:web:4a0aa6dc09f912a8ed33dd',
    messagingSenderId: '578243094632',
    projectId: 'app-notificador-74afb',
    authDomain: 'app-notificador-74afb.firebaseapp.com',
    storageBucket: 'app-notificador-74afb.firebasestorage.app',
    measurementId: 'G-M6BX2VS4W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHlQCaIPBmNIbg0g0qHZQ4gCdDorThzhY',
    appId: '1:578243094632:android:975f871a8fc42a8ded33dd',
    messagingSenderId: '578243094632',
    projectId: 'app-notificador-74afb',
    storageBucket: 'app-notificador-74afb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMJeotrf19LmbRPoPqiBYmw7eEr1hC0mk',
    appId: '1:578243094632:ios:cc2faca16074e61aed33dd',
    messagingSenderId: '578243094632',
    projectId: 'app-notificador-74afb',
    storageBucket: 'app-notificador-74afb.firebasestorage.app',
    iosBundleId: 'com.example.notificador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMJeotrf19LmbRPoPqiBYmw7eEr1hC0mk',
    appId: '1:578243094632:ios:cc2faca16074e61aed33dd',
    messagingSenderId: '578243094632',
    projectId: 'app-notificador-74afb',
    storageBucket: 'app-notificador-74afb.firebasestorage.app',
    iosBundleId: 'com.example.notificador',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhxNKhmZ-xPAIXVbMuCTtsKyG4qMyXGR0',
    appId: '1:578243094632:web:e99c81fd1b5aed02ed33dd',
    messagingSenderId: '578243094632',
    projectId: 'app-notificador-74afb',
    authDomain: 'app-notificador-74afb.firebaseapp.com',
    storageBucket: 'app-notificador-74afb.firebasestorage.app',
    measurementId: 'G-2YG9FTRGNP',
  );

}